// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWJWOprZo5foH7nb83_kjl4WeSXy16PJ4',
    appId: '1:276158793060:web:4c3d0ff47bfbbdd4b46671',
    messagingSenderId: '276158793060',
    projectId: 'fluteerfirebase',
    authDomain: 'fluteerfirebase.firebaseapp.com',
    storageBucket: 'fluteerfirebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASU72cTGkCo86DwvDxOk3nhxPJtYTCEnE',
    appId: '1:276158793060:android:88b98c039fa306a7b46671',
    messagingSenderId: '276158793060',
    projectId: 'fluteerfirebase',
    storageBucket: 'fluteerfirebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-TQC7Mdo9CNELuxWPvFAMr1gpjGA3-qw',
    appId: '1:276158793060:ios:8205dc837f780a79b46671',
    messagingSenderId: '276158793060',
    projectId: 'fluteerfirebase',
    storageBucket: 'fluteerfirebase.firebasestorage.app',
    iosBundleId: 'com.example.actividadaFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-TQC7Mdo9CNELuxWPvFAMr1gpjGA3-qw',
    appId: '1:276158793060:ios:8205dc837f780a79b46671',
    messagingSenderId: '276158793060',
    projectId: 'fluteerfirebase',
    storageBucket: 'fluteerfirebase.firebasestorage.app',
    iosBundleId: 'com.example.actividadaFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWJWOprZo5foH7nb83_kjl4WeSXy16PJ4',
    appId: '1:276158793060:web:c5ad8000666505fdb46671',
    messagingSenderId: '276158793060',
    projectId: 'fluteerfirebase',
    authDomain: 'fluteerfirebase.firebaseapp.com',
    storageBucket: 'fluteerfirebase.firebasestorage.app',
  );
}
